services:
  dddmr_laptop:
    image: dddmr:x64
    container_name: dddmr_jazzy_laptop
    restart: unless-stopped
    privileged: true
    network_mode: host
    ipc: host
    env_file:
      - config/net_laptop.env
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - /dev:/dev
      - /tmp:/tmp
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ${HOME}/dddmr_bags:/root/dddmr_bags
      - ${HOME}/dddmr_navigation:/root/dddmr_navigation
    stdin_open: true
    tty: true
    command: >
      bash -c "source /opt/ros/jazzy/setup.bash &&
               source /root/dddmr_navigation/install/setup.bash &&
               ros2 run rviz2 rviz2 -d /root/dddmr_navigation/src/dddmr_lego_loam/lego_loam_bor/rviz/lego_loam.rviz"
